### ISSUE TITLE
Enable TLS / https

### ISSUE THREAD

**Issue by jonathancross** [CommonAccord/Site-Org#41]
Would be great to add a secure certificate so users can be sure that we are connected to the right site.  Let's Encrypt is recommended: https://letsencrypt.org

**Comment by jonathancross** [comment]
Seems this is incorrect repo. :-(

**Comment by HazardJ** [comment]
Yes, sorry. This repo has been abandoned.  Now Cmacc-Org.

**Comment by jonathancross** [comment]
Maybe delete?
